### ISSUE TITLE
Error on startup because gui_hooks does not exist in Anki 2.1.15's __init__.py

### ISSUE THREAD

**Issue by Alaharon123** [Ajatt-Tools/FlexibleGrading#1]
Does not work on Anki version 2.1.15. Anki starts with the following error and does not run the plugin
>File "/home/\<redacted\>/.local/share/Anki2/addons21/1715096333/answer_buttons.py", line 27, in \<module\>
    from aqt import gui_hooks
>ImportError: cannot import name 'gui_hooks' from 'aqt' (/usr/share/anki/aqt/\_\_init\_\_.py)

I searched \_\_init\_\_.py and indeed there is nothing in the file called gui_hooks

**Comment by tatsumoto-ren** [comment]
This error is not surprising to me because Anki 2.1.15 was released almost 2 years ago. At the very least please use 2.1.35.

**Comment by tatsumoto-ren** [comment]
I've updated the version requirements on AnkiWeb.
